name: Check Melon Ticket (Python)

on:
  schedule:
    - cron: '*/5 * * * *'  # 매 5분마다 실행
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests slack_sdk

      - name: Run ticket checker
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python check_ticket.py
